### ISSUE TITLE
Create RecordFlux specification for TLS 1.3

### ISSUE THREAD

**Issue by treiher** [Componolit/GreenTLS#1]
Specify TLS 1.3 ([RFC8446](https://tools.ietf.org/html/rfc8446))

**Comment by senier** [comment]
I know that you've created specifications for TLS in the *issue_1* branch. What is missing from those specifications to consider this issue done?

**Comment by treiher** [comment]
The specification of concrete extensions is missing. Also the correctness of the existing specification is not completely tested.

**Comment by senier** [comment]
Core TLS standard is done

**Comment by treiher** [comment]
- [ ] Bring the TLS 1.3 specification of Fizz to master
